export const MEMBERSHIP_PLAN = {
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  HALF_YEARLY: "HALF_YEARLY",
  YEARLY: "YEARLY",
} as const;

export const PAYMENT_STATUS = {
  PAID: "PAID",
  PENDING: "PENDING",
  OVERDUE: "OVERDUE",
} as const;

export const NOTIFICATION_TYPE = {
  MEMBERSHIP_RENEWAL: "MEMBERSHIP_RENEWAL",
  PAYMENT_REMINDER: "PAYMENT_REMINDER",
  ATTENDANCE_REMINDER: "ATTENDANCE_REMINDER",
  DIET_PLAN_UPDATED: "DIET_PLAN_UPDATED",
  WORKOUT_PLAN_UPDATED: "WORKOUT_PLAN_UPDATED",
  GENERAL: "GENERAL",
} as const;